name: Main CI workflow
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Create semantic version
      id: semantic-version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        format: "${major}.${minor}.${patch}"
        bump_each_commit: true
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      working-directory: ./agent-app-FE
      run: |
        npm install
    - name: Build BE
      working-directory: ./agent-be
      run: go build -v ./...
      

    - name: Build FE
      working-directory: ./agent-app-FE
      run: |
        npm run build
    - name: Unit test
      working-directory: ./agent-be
      run: go test -v -run=".+UnitTestsSuite" ./...

    - name: Integration tests
      working-directory: ./agent-be
      run: docker-compose -f docker-compose.test.yml up --exit-code-from agent-server-test
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest, ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.semantic-version.outputs.version }}

    - name: Build backend artifact
      working-directory: ./agent-be
      run: go build -o ./agent-be-${{ steps.semantic-version.outputs.version }}.exe ./src/main.go
      
    - name: Build frontend artifact
      working-directory: ./agent-app-FE
      run: |
        npm ci
        CI=false npm run build --if-present

    - name: Upload backend artifact
      uses: actions/upload-artifact@v2
      with:
        name: agent-be-${{ steps.semantic-version.outputs.version }}
        path: ./agent-be/agent-be-${{ steps.semantic-version.outputs.version }}.exe
        
    - name: Upload frontend artifact
      uses: actions/upload-artifact@v2
      with: 
        name: agent-app-FE-${{ steps.versioning.outputs.version }}
        path: ./agent-app-FE/build
